run:
  tests: true

issues:
  max-same-issues: 0
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/leonidkit/word-of-wisdom)

  revive:
    rules:
      - name: unexported-return
        severity: warning
        disabled: true

  lll:
    tab-width: 1
    line-length: 130

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
        toml: snake

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - revive
    - ineffassign
    - lll
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
    - ginkgolinter
    - testifylint
    - gochecksumtype

    # Broken due to https://github.com/golangci/golangci-lint/issues/3711
    # - bodyclose
    # - contextcheck
    # - nilerr
    # - noctx
    # - rowserrcheck
    # - sqlclosecheck
    # - tparallel
    # - unparam
    # - wastedassign
